backend:
  name: github
  repo: bako1/smex
  branch: main
  site_domain: bako1.github.io

media_folder: "src/assets/uploads"
public_folder: "/smex/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/assets/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
