backend:
  name: github
  repo: bako1/smex # change this if your repo name or username is different
  branch: main # where your content (e.g., markdown) lives
  site_domain: bako1.github.io

media_folder: "src/assets/uploads"
public_folder: "/smex/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/assets/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
